// components/GithubIList/GithubList.tsx
import * as React from 'react';
import styles from './GithubList.css';
import globalStyles from './../Layout/Layout.css';
import { GithubItem } from '../../interfaces';
import classnames from 'classnames';

type Props = {
    items: GithubItem[];
    linkText: string;
    title: string;
    gist?: boolean;
};

type State = {
    open: boolean;
};

class PageGithubList extends React.Component<Props, State> {
    constructor(props: Props) {
        super(props);

        this.state = {
            open: false,
        };
        this.onClick = this.onClick.bind(this);
    }

    onClick() {
        this.setState({
            open: !this.state.open,
        });
    }

    render() {
        const { title, items, gist, linkText } = this.props;
        return (
            <div className={styles.github}>
                <h3>{title}</h3>
                <ul className={styles.githubList} ref="">
                    {items
                        ? items.map((item, index) => (
                              <li
                                  data-aos="fade-in"
                                  key={item.id}
                                  className={classnames(
                                      styles.githubItem,
                                      !this.state.open && index >= 6
                                          ? styles.githubItemHidden
                                          : '',
                                  )}>
                                  <div>
                                      <h4>
                                          {gist
                                              ? item.description
                                              : item.full_name}
                                      </h4>
                                      {!gist ? <p>{item.description}</p> : ''}
                                  </div>
                                  <a
                                      href={item.html_url}
                                      className={classnames(
                                          globalStyles.btn,
                                          gist ? globalStyles.btnSecondary : '',
                                      )}
                                      target="_blank"
                                      rel="noopener">
                                      {linkText}
                                  </a>
                              </li>
                          ))
                        : ''}
                </ul>
                <div style={{ textAlign: 'center' }}>
                    <button
                        onClick={this.onClick}
                        className={[
                            globalStyles.btn,
                            gist ? globalStyles.btnSecondary : [],
                        ].join(' ')}>
                        {this.state.open ? 'Verbergen' : 'Alle anzeigen'}
                    </button>
                </div>
            </div>
        );
    }
}

export default PageGithubList;

// components/GithubList.vue
<template>
    <div class="github">
        <h3>{{ title }}</h3>
        <ul class="githubList">
            <li
                v-for="(item, index) in items"
                :key="item.id"
                v-in-viewport.once
                class="githubItem"
                :class="{ githubItemHidden: !open && index >= 6 }"
            >
                <card>
                    <div>
                        <h4>{{ gist ? item.description : item.full_name }}</h4>
                        <p v-if="!gist">{{ item.description }}</p>
                    </div>
                    <div style="text-align: right;">
                        <a
                            :href="item.html_url"
                            rel="noreferrer"
                            target="_blank"
                            :class="{ btn: true, btnSecondary: gist }"
                        >
                            {{ linkText }}
                        </a>
                    </div>
                </card>
            </li>
        </ul>
        <div style="text-align: center;">
            <button :class="{ btn: true, btnSecondary: gist }" @click="open = !open">
                {{ open ? 'Verbergen' : 'Alle anzeigen' }}
            </button>
        </div>
    </div>
</template>

<script lang="ts">
    import { Component, Prop, Vue } from 'nuxt-property-decorator';
    import { GithubItem } from '~/types';
    import Card from '~/components/Card.vue';

    @Component({
        components: { Card },
        data() {
            return {
                open: false,
            };
        },
    })
    export default class GithubList extends Vue {
        @Prop() items!: GithubItem[];
        @Prop({ default: false, type: Boolean }) gist!: boolean;
        @Prop() linkText!: string;
        @Prop() title!: string;
    }
</script>

<style scoped>
    .github {
        margin-top: 50px;
    }

    .github h3 {
        text-align: center;
        margin-bottom: 0;
    }

    .githubItem,
    .githubList {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    .githubList {
        display: flex;
        flex-flow: row wrap;
        margin-left: -1rem;
        margin-right: -1rem;
        padding: 1rem;
    }

    .githubItem {
        margin: 1rem;
        min-width: calc((100% / 1) - 2rem);
        max-width: calc((100% / 1) - 2rem);
        transition: opacity 0.5s, transform 0.8s;
    }

    .githubItem.below-viewport {
        opacity: 0;
        transform: scale3d(0.1, 0.1, 0.1);
    }

    .githubItemHidden {
        display: none;
    }

    .githubItem.in-viewport {
        opacity: 1;
        transform: scale3d(1, 1, 1);
    }

    @media (min-width: 40em) {
        .githubItem {
            min-width: calc((100% / 2) - 2rem);
            max-width: calc((100% / 2) - 2rem);
        }
    }

    @media (min-width: 60em) {
        .githubItem {
            min-width: calc((100% / 3) - 2rem);
            max-width: calc((100% / 3) - 2rem);
        }
    }

    h4 {
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
    }
</style>
