// components/Header/Header.tsx
import * as React from 'react';
import styles from './Header.css';
import classnames from 'classnames';
import Rellax from 'rellax';

const PageHeader: React.FunctionComponent = () => {
    React.useEffect(() => {
        new Rellax('.rellax');
    });

    return (
        <header className={classnames(styles.header)}>
            <div className={styles.backgroundWrapper}>
                <div
                    className="background rellax"
                    data-rellax-speed="-5"
                    role="presentation"
                />
            </div>
            <style jsx>{`
                .background {
                    background-position: center center;
                    background-size: cover;
                    position: absolute;
                    top: 0;
                    bottom: 0;
                    left: 0;
                    right: 0;
                    background-image: url(${require('../../assets/images/header.jpg?webp')});
                }
            `}</style>
            <div className={styles.headerContent}>
                <h1 className={styles.h1}>
                    Webentwicker
                    <br />
                    Frontend Ingenieur
                    <br />
                    Designer
                    <br />
                </h1>
                <h3 className={styles.h3}>
                    Innovation, Inspiration, Technik und Leidenschaft
                </h3>
                <img
                    className={styles.headerShape}
                    alt="header shape"
                    src={require('../../assets/images/shape.svg')}
                    width="1442"
                    height="1316"
                />
            </div>
        </header>
    );
};

export default PageHeader;

// components/Header.vue
<template>
    <header
        class="header"
        :style="{ backgroundImage: `url(${require('@/assets/images/header.jpg?webp')})` }"
    >
        <div class="header_content">
            <h1>
                Webentwicker
                <br />Frontend Ingenieur
                <br />Designer
                <br />
            </h1>
            <h3>Innovation, Inspiration, Technik und Leidenschaft</h3>
            <img
                class="header_shape"
                alt="header shape"
                src="@/assets/images/shape.svg"
                width="1442"
                height="1316"
            />
        </div>
    </header>
</template>
<script lang="ts">
    import Vue from 'vue';
    export default Vue.extend({});
</script>

<style lang="postcss">
    .header {
        display: flex;
        min-height: 500px;
        height: 90vh;
        max-height: 1200px;
        background-size: 1200px;
        background-position: center center;
        position: relative;

        @media (min-width: 768px) {
            background-size: cover;
        }
    }

    .header_content {
        width: 100%;
        margin: auto auto 50px;
        padding-left: 1rem;
        padding-right: 1rem;
        position: relative;
        max-width: 1440px;

        @media (min-width: 768px) {
            margin-bottom: 100px;
        }

        h1 {
            position: relative;
            z-index: 2;
            display: inline-block;
            text-align: left;

            @media (min-width: 500px) {
                text-align: right;
            }
        }

        h3 {
            margin-bottom: 0;
            position: relative;
            z-index: 2;
            text-align: left;
            text-shadow: 0 0 5px rgba(0, 0, 0, 0.8), 0 0 10px rgba(0, 0, 0, 0.6);
        }
    }

    .header_shape {
        max-width: none;
        position: absolute;
        width: calc(1000px + 442 * ((100vw - 420px) / 860));
        top: calc(-100px + -200 * ((100vw - 420px) / 860));
        left: calc(-500px + -140 * ((100vw - 420px) / 860));
    }
</style>
