// components/Post.tsx
import Link from 'next/link';
import React from 'react';
import { IPost } from '~/types';

import Card from './Card';
import css from './Post.module.css';

type Props = {
    post: IPost;
};

const Post: React.FunctionComponent<Props> = ({ post }) => {
    return (
        <Card className={css.article}>
            <div className={css.image}>
                <img
                    src={`${post?.fields?.image?.fields.file.url}?fm=webp&w=600&h=337`}
                    className={css.articleImage}
                    alt="Article image"
                    width="600"
                    height="337"
                />
            </div>
            <div className={css.body}>
                <h4>{post.fields.headline}</h4>
                <time className={css.articleTime} dateTime={post.sys.createdAt}>
                    {new Date(post.sys.createdAt).toLocaleDateString()}
                </time>
                <p className={css.description}>{post.fields.description}</p>
            </div>
            <div className={css.footer}>
                <Link href={`/blog/${post.fields.slug}`}>Zum Post</Link>
            </div>
        </Card>
    );
};

export default Post;

// components/Post.vue
<template>
    <card v-if="post" v-in-viewport.once class="article">
        <div class="image">
            <img
                :src="`${post.fields.image.fields.file.url}?fm=webp&w=600&h=337`"
                class="articleImage"
                alt="Article image"
                width="600"
                height="337"
            />
        </div>
        <div class="body">
            <h4>{{ post.fields.headline }}</h4>
            <time class="articleTime" :datetime="post.sys.createdAt">
                {{ new Date(post.sys.createdAt).toLocaleDateString() }}
            </time>
            <p class="description">{{ post.fields.description }}</p>
        </div>
        <div class="footer">
            <nuxt-link :to="{ name: 'blog-slug', params: { slug: post.fields.slug } }" class="btn">
                Lesen
            </nuxt-link>
        </div>
    </card>
</template>
<script lang="ts">
    import { Component, Prop, Vue } from 'nuxt-property-decorator';
    import Card from '@/components/Card.vue';
    import { IPost } from '@/types/contentful';

    @Component({
        components: {
            Card,
        },
    })
    export default class Post extends Vue {
        @Prop() post: IPost | undefined;
    }
</script>
<style scoped>
    @import '../assets/css/variables.css';

    h4 {
        margin-bottom: 0;
    }

    time {
        font-size: 0.8rem;
        margin-bottom: 1.5rem;
    }

    .article {
        opacity: 1;
        transition: opacity 0.5s, transform 0.8s;
    }

    .below-viewport {
        opacity: 0;
        transform: scale3d(0.1, 0.1, 0.1);
    }

    .article.in-viewport {
        opacity: 1;
        transform: scale3d(1, 1, 1);
    }

    .articleTime {
        color: var(--color__font--secondary);
    }

    .image {
        position: relative;
        padding-bottom: 56.25%;
        margin-top: -1rem;
        margin-left: -1rem;
        margin-right: -1rem;
    }

    .articleImage {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
    }

    .body {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .footer {
        margin-top: 1rem;
    }

    .description {
        font-style: italic;
    }
</style>
