// src/components/Post.tsx
import Link from 'next/link';
import React from 'react';
import { LazyLoadImage } from 'react-lazy-load-image-component';
import { IPost } from '~/types';

import Button from './Button';
import Card from './Card';
import css from './Post.module.css';

type Props = {
    post: IPost;
};

const Post: React.FunctionComponent<Props> = ({ post }) => {
    return (
        <Card className={css.article}>
            <div className={css.image}>
                <LazyLoadImage
                    src={post.data.thumbnail}
                    alt='Article Bild'
                    title={post.data.title}
                    width={600}
                    height={337}
                    className={css.articleImage}
                />
            </div>
            <div className={css.body}>
                <h4>{post.data.title}</h4>
                <time className={css.articleTime} dateTime={post.data.date}>
                    {new Date(post.data.date).toLocaleDateString()}
                </time>
                <p className={css.description}>{post.data.description}</p>
            </div>
            <div className={css.footer}>
                <Link passHref href='/blog/[slug]' as={`/blog/${post.data.slug}/`}>
                    <Button>Zum Post</Button>
                </Link>
            </div>
        </Card>
    );
};

export default Post;

// components/Post.vue
<template>
    <card v-if="post" class="article">
        <div v-if="post.attributes.image" class="image">
            <img
                v-lazy="`${post.attributes.thumbnail}`"
                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAAFRCAQAAAACiBsCAAADSklEQVR42u3UMQ0AAAzDsJU/6SEogEo2hBzJAYyIBIBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhAYYlAWBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBhgVgWACGBRgWgGEBGBZgWACGBWBYgGEBGBaAYQGGBWBYAIYFGBaAYQEYFmBYAIYFYFiAYQEYFoBhAYYFYFgAhgUYFoBhAYYFYFgAhgUYFoBhARgWYFgAhgVgWIBhARgWgGEBhgVgWACGBRgWgGEBGBZgWACGBVA8IDABUgzSsTgAAAAASUVORK5CYII="
                class="articleImage"
                alt="Article image"
                width="600"
                height="337"
            />
        </div>
        <div class="body">
            <h4>{{ post.attributes.title }}</h4>
            <time class="articleTime" :datetime="post.attributes.date">
                {{ new Date(post.attributes.date).toLocaleDateString() }}
            </time>
            <p class="description">{{ post.attributes.description }}</p>
        </div>
        <div class="footer">
            <nuxt-link
                :prefetch="false"
                :to="{ name: 'blog-slug', params: { slug: post.attributes.slug } }"
                class="btn"
            >
                Lesen
            </nuxt-link>
        </div>
    </card>
</template>
<script>
    import Card from '@/components/Card.vue';

    export default {
        name: 'Post',
        components: {
            Card,
        },
        props: {
            post: {
                type: Object,
                default: () => {},
            },
        },
    };
</script>
<style scoped>
    @import '../assets/css/variables.css';

    h4 {
        margin-bottom: 0;
    }

    time {
        font-size: 0.8rem;
        margin-bottom: 1.5rem;
    }

    .article {
        opacity: 1;
        transition: opacity 0.5s, transform 0.8s;
    }

    .below-viewport {
        opacity: 0;
        transform: scale3d(0.1, 0.1, 0.1);
    }

    .article.in-viewport {
        opacity: 1;
        transform: scale3d(1, 1, 1);
    }

    .articleTime {
        color: var(--color__font--secondary);
    }

    .image {
        position: relative;
        padding-bottom: 56.25%;
        margin-top: -1rem;
        margin-left: -1rem;
        margin-right: -1rem;
    }

    .articleImage {
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
    }

    .body {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .footer {
        margin-top: 1rem;
    }

    .description {
        font-style: italic;
    }
</style>
