// src/components/Projects.tsx
import { GithubItem } from '~/types';

import GithubList from './GithubList';
import Section from './Section';

type Props = {
    repos?: GithubItem[];
    snippets?: GithubItem[];
};

const description = function () {
    return (
        <>
            <p>
                Hast du dich schon einmal gefragt, wie manche Menschen so schnell programmieren
                können? Oder fehlt dir die Inspiration zu einem kleinen Bereich deiner Seite?
            </p>
            <p>Hier findest du alles, was einem das Leben leichter macht 😊</p>
            <p>
                Meine kleine Snippet Datenbank wird stetig erweitert und überarbeitet, da ich sie
                selbst jeden Tag produktiv nutze. Wenn du einen Fehler findest oder etwas verbessern
                kannst, dann nur her damit.
            </p>
        </>
    );
};

export default function Projects({ repos, snippets }: Props) {
    return (
        <Section
            title='Projekte und Snippets die mir und vielleicht auch dir helfen können.'
            description={description()}>
            <>
                <div id='repositories'>
                    <GithubList items={repos} linkText='zum Repo' title='Repositories' />
                </div>
                <div id='snippets' className='snippets'>
                    <GithubList items={snippets} gist linkText='zum Snippet' title='Snippets' />
                </div>
            </>
        </Section>
    );
}

// components/Projects.vue
<template>
    <section id="projects" class="projects">
        <Shape direction="right" />
        <header class="projects__header">
            <h2>
                Projekte und Snippets die mir und vielleicht auch dir helfen können.
            </h2>
            <p>
                Hast du dich schon einmal gefragt, wie manche Menschen so schnell programmieren
                können? Oder fehlt dir die Inspiration zu einem kleinen Bereich deiner Seite?
            </p>
            <p>Hier findest du alles, was einem das Leben leichter macht 😊</p>
            <p>
                Meine kleine Snippet Datenbank wird stetig erweitert und überarbeitet, da ich sie
                selbst jeden Tag produktiv nutze. Wenn du einen Fehler findest oder etwas verbessern
                kannst, dann nur her damit.
            </p>
        </header>
        <div id="repositories">
            <github-list :items="repos" link-text="zum Repo" title="Repositories" />
        </div>
        <div id="snippets" class="snippets">
            <github-list :items="snippets" gist link-text="zum Snippet" title="Snippets" />
        </div>
    </section>
</template>

<script lang="ts">
    import { Component, Prop, Vue } from 'nuxt-property-decorator';
    import Shape from '@/components/Shape.vue';
    import { GithubItem } from '~/types';
    import GithubList from '~/components/GithubList.vue';

    @Component({
        components: {
            GithubList,
            Shape,
        },
    })
    export default class Projects extends Vue {
        @Prop() repos: GithubItem[];
        @Prop() snippets: GithubItem[];
    }
</script>

<style scoped>
    .projects {
        max-width: 1440px;
        margin-left: auto;
        margin-right: auto;
        margin-top: 150px;
        position: relative;
    }

    .projects__header {
        max-width: 800px;
        margin-left: auto;
        margin-right: auto;
        padding: 1rem;
    }

    .snippets {
        margin-top: 100px;
    }

    @media (min-width: 40em) {
        .projects__header {
            text-align: center;
        }
    }
</style>
