// components/Shape.vue
<template>
    <div data-rellax-speed="-3" class="wrapper rellax">
        <div :class="{ shape: true, shapeLeft: direction === 'left', shapeBootom: bottom }" />
    </div>
</template>

<script lang="ts">
    import Vue from 'vue';
    export default Vue.extend({
        props: {
            direction: {
                type: String,
                default: () => 'right',
            },
            bottom: {
                type: Boolean,
                default: () => false,
            },
        },
    });
</script>

<style scoped>
    .wrapper {
        position: absolute;
        left: calc(-1 * (200vw - 100%) / 2);
        top: -500px;
        z-index: -1;
    }

    .shape {
        height: 873px;
        width: 200vw;
        transform: rotate(20deg);
        background-image: linear-gradient(
            180deg,
            rgba(255, 255, 255, 0) 0%,
            rgba(255, 255, 255, 0.03) 100%
        );
    }

    .shapeLeft {
        transform: rotate(-20deg);
    }

    .shapeBottom {
        top: auto;
        bottom: 20%;
    }
</style>

// components/Shape/Shape.tsx
import React from 'react';
import classnames from 'classnames';
import styles from './Shape.css';

interface Props {
    direction: 'left' | 'right';
    bottom?: boolean;
}

export const Shape: React.FunctionComponent<Props> = (props) => {
    return (
        <div
            className={classnames(styles.wrapper, 'rellax')}
            data-rellax-speed="-3">
            <div
                className={classnames(
                    styles.shape,
                    props.direction === 'left' ? styles.shapeLeft : '',
                    props.bottom ? styles.shapeBottom : '',
                )}
            />
        </div>
    );
};
